### ISSUE TITLE
Problem during reasoning

### ISSUE THREAD

**Issue by angel-ayala** [Yuchen413/AnomalyRuler#3]
Hi,

I executed the step 4 as follows:
```bash
python main.py --data='SHTech' --deduct
```

And I'm getting this error:
```
Traceback (most recent call last):
  File "/home/angel/desarrollo/AnomalyRuler/main.py", line 103, in <module>
    main()
  File "/home/angel/desarrollo/AnomalyRuler/main.py", line 64, in main
    preds = mixtral_double_deduct(data_name,f'{data_name}/modified_test_frame_description/{name}.txt',
  File "/home/angel/desarrollo/AnomalyRuler/llm.py", line 245, in mixtral_double_deduct
    ini_pred, _, anomaly_keyword = cluster_keyword(obj)
TypeError: cluster_keyword() missing 1 required positional argument: 'anomaly_from_rule'
```

How should I define `anomaly_from_rule`? apparently you missed the argument when call the `cluster_keyword()` function.

**Comment by Yuchen413** [comment]
Hello, please use the latest version and this issue has been solved. Thank you!
